export const Categories = [
  'General knowledge',
  'Entertainment: Books',
  'Entertainment: Film',
  'Entertainment: Music',
  'Entertainment: Musicals & Theatres',
  'Entertainment: Television',
  'Entertainment: Video Games',
  'Entertainment: Board Games',
  'Entrtainement: Comics',
  'Entertainment: Japanese Anime & Manga',
  'Entertainment: Cartoon & Animations',
  'Science & Nature',
  'Science: Computers',
  'Science: Mathematics',
  'Science: Gadgets',
  'Mythology',
  'Sports',
  'Geography',
  'Hystory',
  'Politics',
  'Art',
  'Celebrities',
  'Animals',
  'Vehicles',
];

export const Difficulties = ['Easy', 'Medium', 'Hard'];
